# Copyright (c) Sensrad 2023

axis_temp:
  width: 1920
  height: 1080
  f_x: 990.10146394
  c_x: 973.2097017
  f_y: 996.28128966
  c_y: 540.71478032
  d_1: -1.30001907e+00
  d_2: 5.81700220e-01
  d_3: -6.07227799e-05
  d_4: 1.71482487e-04
  d_5: 1.63717726e-01
  d_6: -9.40322441e-01
  d_7: 4.19079431e-02
  d_8: 4.76514706e-01
  distortion_model: "rational_polynomial"
